### ISSUE TITLE
change project name

### ISSUE THREAD

**Issue by CodeDotJS** [rabingaire/github-init#7]
You need to change the name of this project because the project name `github` is already taken on `npm`

Either you change the whole GitHub URL along with the name in `npm's package.json` file or just tweak the `package.json` file and give it a suitable name. 

You can make it __`repogit`__ or anything else you like but the name should be available on npm.

**Comment by rabingaire** [comment]
I agree with you I will do it :)

**Comment by rabingaire** [comment]
I published it https://www.npmjs.com/package/init-github
